# Generated by Django 6.0.6 on 2026-06-06 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vibe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood', models.CharField(max_length=50)),
                ('energy', models.IntegerField()),
                ('time_of_day', models.IntegerField(max_length=50)),
                ('recommendation', models.CharField(max_length=200)),
                ('date', models.DateField()),
            ],
        ),
    ]
